### ISSUE TITLE
[Feat] 피드 컴포넌트 마이그레이션 및 리팩토링

### ISSUE THREAD

**Issue by jungyoeal** [prgrms-be-devcourse/NBB1_2_3_Team10#22]
## 📍 이슈
피드 관련 컴포넌트를 코틀린으로 마이그레이션하고,
작성한 ERD에 맞추어 구조 변경 및 리팩토링을 수행합니다.

## ☑️ 체크리스트
- [ ] 피드 컴포넌트 마이그레이션
- [ ] 작성한 ERD에 맞추어 구조 변경
- [ ] 비즈니스 로직 수정 및 리팩토링

## 🏷️ 관련 요구사항
작업을 이어받았습니다. (이정우 -> 박주원)

## 📌 기타
오늘 안에 작업 완료하겠습니다.

**Comment by juwon-code** [comment]
정우님께서 하던 작업을 이어받겠습니다.
